import { TypographyOptions } from "../types/typography";
import { fontFamily } from "./fonts";

export const TypographyVariantMapping = {
  h1: "h1",
  h2: "h2",
  h3: "h3",
  h4: "h4",
  h5: "h5",
  h6: "h6",
  subtitle1: "h6",
  subtitle2: "h6",
  body1: "p",
  body2: "p",
  body3: "p",
  inherit: "p",
  buttonLarge: "span",
  buttonMedium: "span",
  buttonSmall: "span",
  caption: "span",
  avatarLetter: "span",
  inputText1: "span",
  inputText2: "span",
  alertTitle: "span",
  tableHeader1: "span",
  tableHeader2: "span",
  inputLabel: "span",
  chip: "span",
  helperText: "span",
  badge: "span",
  tooltip: "span",
};

const baseFontWeight = {
  fontWeightExtraLight: 200,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightSemiBold: 600,
  fontWeightBold: 700,
  fontWeightExtraBold: 800,
  fontWeightBlack: 900,
};

export const fleetTypography: TypographyOptions = {
  fontFamily,
  htmlFontSize: 16,
  fontSize: 17,
  h1: {
    fontFamily,
    fontSize: "4rem",
    fontWeight: baseFontWeight.fontWeightLight,
    lineHeight: "5rem",
    letterSpacing: "-0.094rem",
  },
  h2: {
    fontFamily,
    fontSize: "3rem",
    fontWeight: baseFontWeight.fontWeightRegular,
    lineHeight: "3.75rem",
    letterSpacing: "-0.063rem",
  },
  h3: {
    fontFamily,
    fontSize: "2.5rem",
    fontWeight: baseFontWeight.fontWeightRegular,
    lineHeight: "3rem",
    letterSpacing: "-0.031rem",
  },
  h4: {
    fontFamily,
    fontSize: "2rem",
    fontWeight: baseFontWeight.fontWeightRegular,
    lineHeight: "2.5rem",
    letterSpacing: "-0.031rem",
  },
  h5: {
    fontFamily,
    fontSize: "1.5rem",
    fontWeight: baseFontWeight.fontWeightSemiBold,
    lineHeight: "2rem",
    letterSpacing: "0rem",
  },
  h6: {
    fontFamily,
    fontSize: "1.25rem",
    fontWeight: baseFontWeight.fontWeightSemiBold,
    lineHeight: "1.75rem",
    letterSpacing: "0rem",
  },
  subtitle1: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  subtitle2: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  body1: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  body1Semibold: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  body1Bold: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  body2: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 400,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  body2Semibold: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  body2Bold: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 700,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  body3: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 400,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  body3Semibold: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  body3Bold: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 800,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  body4Semibold: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  caps1: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: "1.5rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps1Bold: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: "1.5rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps2: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 400,
    lineHeight: "1.25rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps2Bold: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 700,
    lineHeight: "1.25rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps3: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 400,
    lineHeight: "1.125rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps3Bold: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 700,
    lineHeight: "1.125rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps4: {
    fontFamily,
    fontSize: "0.625rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  caps4Bold: {
    fontFamily,
    fontSize: "0.625rem",
    fontWeight: 700,
    lineHeight: "1.125rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  buttonLarge: {
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  buttonMedium: {
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  buttonSmall: {
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  caption: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 400,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  overline: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 700,
    lineHeight: "1.125rem",
    letterSpacing: "0.06rem",
    textTransform: "uppercase",
  },
  avatarLetter: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  inputText1: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  inputText2: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 400,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  alertTitle: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  tableHeader1: {
    fontFamily,
    fontSize: "1rem",
    fontWeight: 700,
    lineHeight: "1.5rem",
    letterSpacing: "0rem",
  },
  tableHeader2: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 700,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  inputLabel: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 400,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  chip: {
    fontFamily,
    fontSize: "0.875rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
    letterSpacing: "0rem",
  },
  helperText: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 400,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  badge: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
  tooltip: {
    fontFamily,
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    letterSpacing: "0.0156rem",
  },
};
